#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ReittiWidgets.Resource", IsApplication=true)]

namespace ReittiWidgets
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f070000
			public const int spinner_delay_values = 2131165184;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f080004
			public const int DividerGray500 = 2131230724;
			
			// aapt resource value: 0x7f080006
			public const int Highlight = 2131230726;
			
			// aapt resource value: 0x7f080005
			public const int SelectedItem = 2131230725;
			
			// aapt resource value: 0x7f080007
			public const int White = 2131230727;
			
			// aapt resource value: 0x7f080000
			public const int action_bar = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int context_action_bar = 2131230721;
			
			// aapt resource value: 0x7f080003
			public const int secondary_text = 2131230723;
			
			// aapt resource value: 0x7f080002
			public const int window_background = 2131230722;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050000
			public const int activity_horizontal_margin = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int activity_vertical_margin = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int widget_margin = 2131034114;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int border = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_action_discard = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_action_new = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_action_refresh = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_launcher = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_main = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int selected_item = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int widget_preview = 2130837511;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0b0024
			public const int action_add_line = 2131427364;
			
			// aapt resource value: 0x7f0b0027
			public const int action_delete_stop = 2131427367;
			
			// aapt resource value: 0x7f0b0025
			public const int action_refresh = 2131427365;
			
			// aapt resource value: 0x7f0b000c
			public const int buttonAddline = 2131427340;
			
			// aapt resource value: 0x7f0b000a
			public const int checkBoxShowVersions = 2131427338;
			
			// aapt resource value: 0x7f0b0012
			public const int controlLayout = 2131427346;
			
			// aapt resource value: 0x7f0b0003
			public const int delayLayout = 2131427331;
			
			// aapt resource value: 0x7f0b0004
			public const int delayLayoutInner = 2131427332;
			
			// aapt resource value: 0x7f0b0015
			public const int delaySpinnerEdit = 2131427349;
			
			// aapt resource value: 0x7f0b0026
			public const int deleteStop = 2131427366;
			
			// aapt resource value: 0x7f0b000e
			public const int displayStopInWidget = 2131427342;
			
			// aapt resource value: 0x7f0b0001
			public const int inputStopName = 2131427329;
			
			// aapt resource value: 0x7f0b0005
			public const int labelDelay = 2131427333;
			
			// aapt resource value: 0x7f0b0007
			public const int labelDelayDetail = 2131427335;
			
			// aapt resource value: 0x7f0b0019
			public const int labelFollowingDeparture = 2131427353;
			
			// aapt resource value: 0x7f0b0020
			public const int labelFollowingDepartureWidget = 2131427360;
			
			// aapt resource value: 0x7f0b0013
			public const int labelLineName = 2131427347;
			
			// aapt resource value: 0x7f0b001e
			public const int labelLineNameWidget = 2131427358;
			
			// aapt resource value: 0x7f0b0018
			public const int labelNextDeparture = 2131427352;
			
			// aapt resource value: 0x7f0b001f
			public const int labelNextDepartureWidget = 2131427359;
			
			// aapt resource value: 0x7f0b0009
			public const int labelVersion = 2131427337;
			
			// aapt resource value: 0x7f0b000b
			public const int labelVersionDetail = 2131427339;
			
			// aapt resource value: 0x7f0b0023
			public const int lineItemsHolderWidget = 2131427363;
			
			// aapt resource value: 0x7f0b0011
			public const int lineLayout = 2131427345;
			
			// aapt resource value: 0x7f0b0010
			public const int linesListView = 2131427344;
			
			// aapt resource value: 0x7f0b0000
			public const int searchViewStopName = 2131427328;
			
			// aapt resource value: 0x7f0b000f
			public const int separator = 2131427343;
			
			// aapt resource value: 0x7f0b0016
			public const int showVariantsSwitch = 2131427350;
			
			// aapt resource value: 0x7f0b0002
			public const int spinner = 2131427330;
			
			// aapt resource value: 0x7f0b0006
			public const int spinner2 = 2131427334;
			
			// aapt resource value: 0x7f0b001a
			public const int stopLayout = 2131427354;
			
			// aapt resource value: 0x7f0b0021
			public const int stopLayoutWidget = 2131427361;
			
			// aapt resource value: 0x7f0b001b
			public const int stopNameTextView = 2131427355;
			
			// aapt resource value: 0x7f0b0022
			public const int stopNameTextViewWidget = 2131427362;
			
			// aapt resource value: 0x7f0b0017
			public const int stopsListView = 2131427351;
			
			// aapt resource value: 0x7f0b001d
			public const int stopsWidgetList = 2131427357;
			
			// aapt resource value: 0x7f0b000d
			public const int textView = 2131427341;
			
			// aapt resource value: 0x7f0b0014
			public const int textView2 = 2131427348;
			
			// aapt resource value: 0x7f0b0008
			public const int versionLayout = 2131427336;
			
			// aapt resource value: 0x7f0b001c
			public const int widgetRootLayout = 2131427356;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AddLine = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int addline_list_autocomplete_item = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int EditLine = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int editline_list_line_item = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Main = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int main_list_line_item = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int main_list_stop_item = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Widget = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int widget_line_list_item = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int widget_stop_list_item = 2130903049;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f0a0000
			public const int MainMenu = 2131361792;
			
			// aapt resource value: 0x7f0a0001
			public const int stops_context = 2131361793;
			
			// aapt resource value: 0x7f0a0002
			public const int stops_select_menu = 2131361794;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060000
			public const int ApplicationName = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int WidgetName = 2131099649;
			
			// aapt resource value: 0x7f06000c
			public const int action_add_line = 2131099660;
			
			// aapt resource value: 0x7f06000e
			public const int action_delete = 2131099662;
			
			// aapt resource value: 0x7f060014
			public const int action_desciption_lines_selected = 2131099668;
			
			// aapt resource value: 0x7f060013
			public const int action_desciption_select_lines = 2131099667;
			
			// aapt resource value: 0x7f060011
			public const int action_desciption_select_stops = 2131099665;
			
			// aapt resource value: 0x7f060012
			public const int action_desciption_stops_selected = 2131099666;
			
			// aapt resource value: 0x7f06000d
			public const int action_refresh = 2131099661;
			
			// aapt resource value: 0x7f06000f
			public const int action_settings = 2131099663;
			
			// aapt resource value: 0x7f060005
			public const int add_line = 2131099653;
			
			// aapt resource value: 0x7f060022
			public const int add_widget = 2131099682;
			
			// aapt resource value: 0x7f060002
			public const int app_name = 2131099650;
			
			// aapt resource value: 0x7f060021
			public const int appwidget_text = 2131099681;
			
			// aapt resource value: 0x7f060010
			public const int content_description_remove_line = 2131099664;
			
			// aapt resource value: 0x7f06001d
			public const int db_exists_toast = 2131099677;
			
			// aapt resource value: 0x7f06001c
			public const int db_updated_toast = 2131099676;
			
			// aapt resource value: 0x7f06001e
			public const int enter_stop_name = 2131099678;
			
			// aapt resource value: 0x7f06001b
			public const int line_deleted = 2131099675;
			
			// aapt resource value: 0x7f060018
			public const int loading = 2131099672;
			
			// aapt resource value: 0x7f060019
			public const int no_connection = 2131099673;
			
			// aapt resource value: 0x7f060020
			public const int no_time = 2131099680;
			
			// aapt resource value: 0x7f06001f
			public const int no_timetable_data = 2131099679;
			
			// aapt resource value: 0x7f060015
			public const int searchview_stops_hint = 2131099669;
			
			// aapt resource value: 0x7f060006
			public const int show_versions = 2131099654;
			
			// aapt resource value: 0x7f060008
			public const int show_versions_detail = 2131099656;
			
			// aapt resource value: 0x7f060007
			public const int show_widget = 2131099655;
			
			// aapt resource value: 0x7f06000b
			public const int stop_code = 2131099659;
			
			// aapt resource value: 0x7f06001a
			public const int stop_deleted = 2131099674;
			
			// aapt resource value: 0x7f060017
			public const int stops_context_delete = 2131099671;
			
			// aapt resource value: 0x7f060016
			public const int stops_context_edit = 2131099670;
			
			// aapt resource value: 0x7f060009
			public const int time_delay = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int time_delay_detail = 2131099658;
			
			// aapt resource value: 0x7f060003
			public const int title_activity_add_line = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int title_activity_edit_stop = 2131099652;
			
			// aapt resource value: 0x7f060023
			public const int update_widget = 2131099683;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f090002
			public const int ActionBar = 2131296258;
			
			// aapt resource value: 0x7f090001
			public const int AppTheme = 2131296257;
			
			// aapt resource value: 0x7f090003
			public const int ContextActionBar = 2131296259;
			
			// aapt resource value: 0x7f090000
			public const int Divider = 2131296256;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f040000
			public const int searchable = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int widget_info = 2130968577;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
