#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ReittiWidgets.Resource", IsApplication=true)]

namespace ReittiWidgets
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f060000
			public const int spinner_delay_values = 2131099648;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f070004
			public const int DividerGray500 = 2131165188;
			
			// aapt resource value: 0x7f070006
			public const int Highlight = 2131165190;
			
			// aapt resource value: 0x7f070005
			public const int SelectedItem = 2131165189;
			
			// aapt resource value: 0x7f070007
			public const int White = 2131165191;
			
			// aapt resource value: 0x7f070000
			public const int action_bar = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int context_action_bar = 2131165185;
			
			// aapt resource value: 0x7f070003
			public const int secondary_text = 2131165187;
			
			// aapt resource value: 0x7f070002
			public const int window_background = 2131165186;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f040000
			public const int activity_horizontal_margin = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int activity_vertical_margin = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int widget_margin = 2130968578;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int border = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_action_discard = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_action_new = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_action_refresh = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_launcher = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_main = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int selected_item = 2130837510;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0a001b
			public const int action_add_line = 2131361819;
			
			// aapt resource value: 0x7f0a001e
			public const int action_delete_stop = 2131361822;
			
			// aapt resource value: 0x7f0a001c
			public const int action_refresh = 2131361820;
			
			// aapt resource value: 0x7f0a000b
			public const int buttonAddline = 2131361803;
			
			// aapt resource value: 0x7f0a0009
			public const int checkBoxShowVersions = 2131361801;
			
			// aapt resource value: 0x7f0a0011
			public const int controlLayout = 2131361809;
			
			// aapt resource value: 0x7f0a0002
			public const int delayLayout = 2131361794;
			
			// aapt resource value: 0x7f0a0003
			public const int delayLayoutInner = 2131361795;
			
			// aapt resource value: 0x7f0a0014
			public const int delaySpinnerEdit = 2131361812;
			
			// aapt resource value: 0x7f0a001d
			public const int deleteStop = 2131361821;
			
			// aapt resource value: 0x7f0a000d
			public const int displayStopInWidget = 2131361805;
			
			// aapt resource value: 0x7f0a0000
			public const int inputStopName = 2131361792;
			
			// aapt resource value: 0x7f0a0004
			public const int labelDelay = 2131361796;
			
			// aapt resource value: 0x7f0a0006
			public const int labelDelayDetail = 2131361798;
			
			// aapt resource value: 0x7f0a0018
			public const int labelFollowingDeparture = 2131361816;
			
			// aapt resource value: 0x7f0a0012
			public const int labelLineName = 2131361810;
			
			// aapt resource value: 0x7f0a0017
			public const int labelNextDeparture = 2131361815;
			
			// aapt resource value: 0x7f0a0008
			public const int labelVersion = 2131361800;
			
			// aapt resource value: 0x7f0a000a
			public const int labelVersionDetail = 2131361802;
			
			// aapt resource value: 0x7f0a0010
			public const int lineLayout = 2131361808;
			
			// aapt resource value: 0x7f0a000f
			public const int linesListView = 2131361807;
			
			// aapt resource value: 0x7f0a000e
			public const int separator = 2131361806;
			
			// aapt resource value: 0x7f0a0015
			public const int showVariantsSwitch = 2131361813;
			
			// aapt resource value: 0x7f0a0001
			public const int spinner = 2131361793;
			
			// aapt resource value: 0x7f0a0005
			public const int spinner2 = 2131361797;
			
			// aapt resource value: 0x7f0a0019
			public const int stopLayout = 2131361817;
			
			// aapt resource value: 0x7f0a001a
			public const int stopNameTextView = 2131361818;
			
			// aapt resource value: 0x7f0a0016
			public const int stopsListView = 2131361814;
			
			// aapt resource value: 0x7f0a000c
			public const int textView = 2131361804;
			
			// aapt resource value: 0x7f0a0013
			public const int textView2 = 2131361811;
			
			// aapt resource value: 0x7f0a0007
			public const int versionLayout = 2131361799;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AddLine = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int addline_list_autocomplete_item = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int EditLine = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int editline_list_line_item = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Main = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int main_list_line_item = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int main_list_stop_item = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f090000
			public const int MainMenu = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int stops_context = 2131296257;
			
			// aapt resource value: 0x7f090002
			public const int stops_select_menu = 2131296258;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int ApplicationName = 2131034112;
			
			// aapt resource value: 0x7f05000b
			public const int action_add_line = 2131034123;
			
			// aapt resource value: 0x7f05000d
			public const int action_delete = 2131034125;
			
			// aapt resource value: 0x7f050013
			public const int action_desciption_lines_selected = 2131034131;
			
			// aapt resource value: 0x7f050012
			public const int action_desciption_select_lines = 2131034130;
			
			// aapt resource value: 0x7f050010
			public const int action_desciption_select_stops = 2131034128;
			
			// aapt resource value: 0x7f050011
			public const int action_desciption_stops_selected = 2131034129;
			
			// aapt resource value: 0x7f05000c
			public const int action_refresh = 2131034124;
			
			// aapt resource value: 0x7f05000e
			public const int action_settings = 2131034126;
			
			// aapt resource value: 0x7f050004
			public const int add_line = 2131034116;
			
			// aapt resource value: 0x7f050020
			public const int add_widget = 2131034144;
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f05001f
			public const int appwidget_text = 2131034143;
			
			// aapt resource value: 0x7f05000f
			public const int content_description_remove_line = 2131034127;
			
			// aapt resource value: 0x7f05001b
			public const int db_exists_toast = 2131034139;
			
			// aapt resource value: 0x7f05001a
			public const int db_updated_toast = 2131034138;
			
			// aapt resource value: 0x7f05001c
			public const int enter_stop_name = 2131034140;
			
			// aapt resource value: 0x7f050019
			public const int line_deleted = 2131034137;
			
			// aapt resource value: 0x7f050016
			public const int loading = 2131034134;
			
			// aapt resource value: 0x7f050017
			public const int no_connection = 2131034135;
			
			// aapt resource value: 0x7f05001e
			public const int no_time = 2131034142;
			
			// aapt resource value: 0x7f05001d
			public const int no_timetable_data = 2131034141;
			
			// aapt resource value: 0x7f050005
			public const int show_versions = 2131034117;
			
			// aapt resource value: 0x7f050007
			public const int show_versions_detail = 2131034119;
			
			// aapt resource value: 0x7f050006
			public const int show_widget = 2131034118;
			
			// aapt resource value: 0x7f05000a
			public const int stop_code = 2131034122;
			
			// aapt resource value: 0x7f050018
			public const int stop_deleted = 2131034136;
			
			// aapt resource value: 0x7f050015
			public const int stops_context_delete = 2131034133;
			
			// aapt resource value: 0x7f050014
			public const int stops_context_edit = 2131034132;
			
			// aapt resource value: 0x7f050008
			public const int time_delay = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int time_delay_detail = 2131034121;
			
			// aapt resource value: 0x7f050002
			public const int title_activity_add_line = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int title_activity_edit_stop = 2131034115;
			
			// aapt resource value: 0x7f050021
			public const int update_widget = 2131034145;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080002
			public const int ActionBar = 2131230722;
			
			// aapt resource value: 0x7f080001
			public const int AppTheme = 2131230721;
			
			// aapt resource value: 0x7f080003
			public const int ContextActionBar = 2131230723;
			
			// aapt resource value: 0x7f080000
			public const int Divider = 2131230720;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
