#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ReittiWidgets.Resource", IsApplication=true)]

namespace ReittiWidgets
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f070000
			public const int spinner_delay_values = 2131165184;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050000
			public const int activity_horizontal_margin = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int activity_vertical_margin = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int widget_margin = 2131034114;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_action_discard = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_action_new = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_action_refresh = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_main = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f09000d
			public const int action_add_line = 2131296269;
			
			// aapt resource value: 0x7f09000e
			public const int action_refresh = 2131296270;
			
			// aapt resource value: 0x7f09000b
			public const int buttonAddline = 2131296267;
			
			// aapt resource value: 0x7f090009
			public const int checkBoxShowVersions = 2131296265;
			
			// aapt resource value: 0x7f090002
			public const int delayLayout = 2131296258;
			
			// aapt resource value: 0x7f090003
			public const int delayLayoutInner = 2131296259;
			
			// aapt resource value: 0x7f090000
			public const int inputStopName = 2131296256;
			
			// aapt resource value: 0x7f090004
			public const int labelDelay = 2131296260;
			
			// aapt resource value: 0x7f090006
			public const int labelDelayDetail = 2131296262;
			
			// aapt resource value: 0x7f090008
			public const int labelVersion = 2131296264;
			
			// aapt resource value: 0x7f09000a
			public const int labelVersionDetail = 2131296266;
			
			// aapt resource value: 0x7f090001
			public const int spinner = 2131296257;
			
			// aapt resource value: 0x7f090005
			public const int spinner2 = 2131296261;
			
			// aapt resource value: 0x7f09000c
			public const int stopsListView = 2131296268;
			
			// aapt resource value: 0x7f090007
			public const int versionLayout = 2131296263;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AddLine = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f080000
			public const int MainMenu = 2131230720;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int ApplicationName = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int Hello = 2131099648;
			
			// aapt resource value: 0x7f06000c
			public const int action_add_line = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int action_settings = 2131099661;
			
			// aapt resource value: 0x7f060005
			public const int add_line = 2131099653;
			
			// aapt resource value: 0x7f060018
			public const int add_widget = 2131099672;
			
			// aapt resource value: 0x7f060002
			public const int app_name = 2131099650;
			
			// aapt resource value: 0x7f060017
			public const int appwidget_text = 2131099671;
			
			// aapt resource value: 0x7f06000e
			public const int content_description_remove_line = 2131099662;
			
			// aapt resource value: 0x7f060014
			public const int db_exists_toast = 2131099668;
			
			// aapt resource value: 0x7f060013
			public const int db_updated_toast = 2131099667;
			
			// aapt resource value: 0x7f060015
			public const int enter_stop_name = 2131099669;
			
			// aapt resource value: 0x7f060011
			public const int no_connection = 2131099665;
			
			// aapt resource value: 0x7f060016
			public const int no_time = 2131099670;
			
			// aapt resource value: 0x7f060006
			public const int show_versions = 2131099654;
			
			// aapt resource value: 0x7f060008
			public const int show_versions_detail = 2131099656;
			
			// aapt resource value: 0x7f060007
			public const int show_widget = 2131099655;
			
			// aapt resource value: 0x7f06000b
			public const int stop_code = 2131099659;
			
			// aapt resource value: 0x7f060012
			public const int stop_deleted = 2131099666;
			
			// aapt resource value: 0x7f060010
			public const int stops_context_delete = 2131099664;
			
			// aapt resource value: 0x7f06000f
			public const int stops_context_edit = 2131099663;
			
			// aapt resource value: 0x7f060009
			public const int time_delay = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int time_delay_detail = 2131099658;
			
			// aapt resource value: 0x7f060003
			public const int title_activity_add_line = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int title_activity_edit_stop = 2131099652;
			
			// aapt resource value: 0x7f060019
			public const int update_widget = 2131099673;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f040000
			public const int stops = 2130968576;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
